name: 🏗️ Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
      
        # Install Node 
      - name: 📥 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: npm
      
        # Install Java
      - name: 📥 Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      
        # Install Gradle
      - name: 📥 Install Gradle
        uses: gradle/gradle-build-action@v2.12.0
        with:
          gradle-version: 7.6
        
        # Install apksigner
      - name: 📥 Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

        # Install NPM dependencies
      - name: 📥 Install NPM Dependencies
        run: npm ci
        
        # Decode keystore
      - name: 🔑 Decode keystore
        run: |
          mkdir -p ./android/keystore/
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ./android/keystore/release.keystore
        
        # Build APK
      - name: 🏗️ Build APK
        run: |
          npm run build:release
          rm -rf ./android/keystore/release.keystore
          
          mv ./android/app/build/outputs/apk/release/app-release-signed.apk ./android/app/build/outputs/apk/release/SEGES+.apk
          rm -rf ./android/app/build/outputs/apk/release/app-release-unsigned.apk

        env:
          KEYSTOREPASS: ${{ secrets.KEYSTOREPASS }}
          KEYSTOREALIASPASS: ${{ secrets.KEYSTOREALIASPASS }}
          KEYSTOREALIAS: ${{ secrets.KEYSTOREALIAS }}
          WORKFLOW: true
        
        # Create draft release
      - name: 📤 Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
